version: "3.8"

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    command: /start.sh
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - .:/home/api
      - static_volume:/home/api/static
    environment:
      DJANGO_SETTINGS_MODULE: main.settings.dev
      DJANGO_READ_DOT_ENV_FILE: "off"
      DJANGO_DEBUG: "on"
      SECRET_KEY: your-secret-key
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
